const types = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    ADD_CART: "ADD_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    FETCH_USERS: "FETCH_USERS",
    LOGOUT: "LOGOUT"
};
export default types;